services:
  speech-service:
    mem_limit: 2000m
    cpus: "1"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-service
    networks:
      - tts_network
    ports:
      - '127.0.0.1:8000:8000'
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [cuda]
networks:
  tts-network:
    driver: bridge